<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlowEncode.Application\FlowEncode.Application.csproj" />
    <ProjectReference Include="..\FlowEncode.Domain\FlowEncode.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
